import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Modal from '../components/Modal'


export default function Home() {
  return (
    <div className='bg-gray-100 h-screen overflow-y-scroll scrollbar-hide  '>
      <Head>
        <title>Instagach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Instagram_icon.png.webp" />
      </Head>

      <main >
       {/*Header */}
       <Header/>
       {/*Hero */}
       <Hero/>
       {/*Modal */}
        <Modal/>
      </main>

     
    </div>
  )
}
